version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./core/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: core/nginx/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
    ports:
      - '${DB_PORT}:3306'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci